### ISSUE TITLE
Unsupported fd type: TTY 

### ISSUE THREAD

**Issue by jedi4ever** [c3ks/node-webterminal#3]
FYI  - running nodejs 0.10.x with the plain github version, result in this error when a browser client connects. 

```
New Connection opened                                                                                                                          

net.js:50                                                                                                                                      
  throw new TypeError('Unsupported fd type: ' + type);                                                                                         
        ^                                                                                                                                      
TypeError: Unsupported fd type: TTY                                                                                                            
    at createHandle (net.js:50:9)                                                                                                              
    at new Socket (net.js:156:20)                                                                                                              
    at new Terminal (/Users/patrick/dev/node-webterminal/node_modules/pty.js/lib/pty.js:63:17)                                                 
    at Function.Terminal.fork.Terminal.spawn.Terminal.createTerminal (/Users/patrick/dev/node-webterminal/node_modules/pty.js/lib/pty.js:112:10
)                                                                                                                                              
    at Object.PtyController.init (/Users/patrick/dev/node-webterminal/controllers/ptycontroller.js:21:18)                                      
    at Socket.<anonymous> (/Users/patrick/dev/node-webterminal/controllers/ptycontroller.js:8:45)                                              
    at Socket.EventEmitter.emit [as $emit] (events.js:95:17)                                                                                   
    at SocketNamespace.handlePacket (/Users/patrick/dev/node-webterminal/node_modules/socket.io/lib/namespace.js:335:22)                       
    at Manager.onClientMessage (/Users/patrick/dev/node-webterminal/node_modules/socket.io/lib/manager.js:488:38)                              
    at WebSocket.Transport.onMessage (/Users/patrick/dev/node-webterminal/node_modules/socket.io/lib/transport.js:387:20)      
```

**Comment by Gottox** [comment]
Fixed, we used an old pty.js version.

**Comment by jedi4ever** [comment]
yep that worked!
